import { StyleSheet, Dimensions } from 'react-native';
const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  imageContainer: {
    height: height * 0.7,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
    backgroundColor: 'rgba(248,248,248,255)',
    paddingTop: 40,
    borderBottomLeftRadius: 70,
    borderBottomRightRadius: 70,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  welcomeText: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#2E8B57',
    marginBottom: 10,
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  Text: {
    fontSize: 18,
    color: '#2E8B30',
    marginBottom: 2,
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  collectorImage: {
    width: '80%',
    height: '80%',
    borderRadius: 10,
  },
  gradient: {
    flex: 1,
  },
  mainContainer: {
    flex: 1, 
    paddingHorizontal: 20,
  },
  header: {
    marginBottom: 30,
    alignItems: 'center',
  },
  headerText: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#2e7d32',
  },
  homeContainer: {
     flex: 1,
    justifyContent: 'flex-end',
    marginTop: 40,
    
  },
  buttonContainer: {
  flexDirection: 'column',  // Stack vertically for better mobile UX
  alignItems: 'center',
  justifyContent: 'center',
  paddingHorizontal: 10,
  marginBottom: 40,
  gap: 20,  // space between buttons
}
,
 optionButton: {
  width: '100%',
  minHeight: 60,
  borderRadius: 12,
  paddingVertical: 16,
  paddingHorizontal: 20,
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'center',
  backgroundColor: '#2E8B57',
  elevation: 5,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.3,
  shadowRadius: 4,
},

logoutButton: {
  position: 'absolute',
  top: -600,           // Adjust as needed (status bar safe)
  right: 4,
  backgroundColor: '#2E8B30',
  padding: 10,
  borderRadius: 20,
  zIndex: 1,        // Ensure it's above other elements
  elevation: 4,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 5 },
  shadowOpacity: 0.2,
  shadowRadius: 4,
},


  cameraFullScreenContainer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cameraInstructionContainer: {
    position: 'absolute',
    top: 50,
    alignItems: 'center',
    width: '100%',
  },
  cameraSquareContainer: {
    width: width * 0.8,
    aspectRatio: 1,
    overflow: 'hidden',
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#2e7d32',
  },
  cameraSquare: {
    flex: 1,
  },
  cameraControls: {
    position: 'absolute',
    bottom: 50,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 30,
  },
  cameraOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scanFrame: {
    width: '80%',
    aspectRatio: 1,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.7)",
    borderRadius: 15,
  },
  scanHelpText: {
    color: '#2e7d32',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 20,
  },
  resultScreen: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  resultText: {
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    padding: 15,
    backgroundColor: 'rgba(255,255,255,0.7)',
    borderRadius: 10,
    color: '#2e7d32',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  permissionContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  permissionText: {
    fontSize: 16,
    marginBottom: 20,
    textAlign: 'center',
    color: '#2e7d32',
  },
  permissionButton: {
    backgroundColor: '#2e7d32',
    padding: 15,
    borderRadius: 8,
    elevation: 3,
  },
  generateButton: {
    backgroundColor: '#2E8B57',
    shadowColor: '#2E8B57',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    padding:30,
  },
  scanButton: {
    backgroundColor: '#2E8B57',
    shadowColor: '#2E8B57',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    padding: 30,
  },
  downloadButton: {
    backgroundColor: '#5e35b1',
  },
  actionButton: {
    padding: 15,
    borderRadius: 10,
    marginVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  backButton: {
    marginBottom: 15,
    flexDirection: 'row',
    alignItems: 'center',
  },
  backText: {
    fontSize: 16,
    color: "#2e7d32",
    marginLeft: 5,
  },
  buttonText: {
    color: "#fff",
    fontWeight: "bold",
    textAlign: "center",
    marginLeft: 8,
    fontSize: 16,
  },
  buttonIcon: {
    marginRight: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: "#81c784",
    padding: 15,
    marginVertical: 10,
    borderRadius: 10,
    backgroundColor: 'white',
    fontSize: 16,
  },
  sectionTitle: {
    fontWeight: "bold",
    marginTop: 10,
    fontSize: 16,
    color: '#2e7d32',
  },
  map: {
    height: 200,
    borderRadius: 10,
    marginVertical: 10,
    borderWidth: 1,
    borderColor: '#81c784',
  },
  label: {
    marginBottom: 10,
    fontSize: 14,
    color: '#2e7d32',
    fontStyle: 'italic',
  },
  qrContainer: {
    alignItems: "center",
    marginTop: 20,
  },
  qrImageContainer: {
    backgroundColor: 'white',
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#81c784',
    marginVertical: 10,
  },
  qrLabel: {
    fontWeight: "bold",
    marginBottom: 10,
    fontSize: 18,
    color: '#2e7d32',
  },
  qrImage: {
    width: 200,
    height: 200,
  },
  errorText: {
    color: '#d32f2f',
  },
  successText: {
    color: '#2e7d32',
  },
  card: {
    backgroundColor: 'white',
    borderRadius: 15,
    padding: 20,
    marginBottom: -5,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    marginTop: 30,
  },
  cardContent: {
    paddingBottom: 20,
  },
  closeCameraButton: {
    backgroundColor: 'rgba(255,255,255,0.7)',
    borderRadius: 30,
    padding: 10,
  },
  flipButton: {
    backgroundColor: 'rgba(255,255,255,0.7)',
    borderRadius: 30,
    padding: 10,
  },
  capacityInput: {
    borderWidth: 1,
    borderColor: "#81c784",
    padding: 15,
    marginVertical: 10,
    borderRadius: 10,
    backgroundColor: 'white',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  capacityText: {
    fontSize: 16,
    color: '#000',
  },
  capacityPlaceholder: {
    fontSize: 16,
    color: '#888',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  dropdownContainer: {
    backgroundColor: 'white',
    marginHorizontal: 20,
    borderRadius: 10,
    padding: 10,
    elevation: 5,
  },
  dropdownOption: {
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  dropdownOptionText: {
    fontSize: 16,
    color: '#2e7d32',
  },
});