import { StyleSheet, Dimensions } from 'react-native';
const { height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "rgb(176, 219, 156)",
    padding: 25,
    paddingTop: 0,
    alignItems: "center",
  },
  imageContainer: {
    height: height * 0.4,
    width: '120%',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 28,
    backgroundColor: 'rgba(240,241,245,255)',
    paddingTop: 60,
    paddingBottom: 30,
    borderBottomLeftRadius: 80,
    borderBottomRightRadius: 80,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  welcomeText: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#2E8B57',
    marginBottom: 55,
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  collectorImage: {
    width: '70%',
    height: '70%',
    borderRadius: 10,
  },
cameraContainer: {
  ...StyleSheet.absoluteFillObject,
  backgroundColor: 'rgba(232, 285, 205, 1)',
  justifyContent: 'center',
  alignItems: 'center',
  zIndex: 100,
},
camera: {
  width: Dimensions.get('window').width - 40,
  height: Dimensions.get('window').width - 40,
  borderRadius: 16,
  overflow: 'hidden',
  borderWidth: 2,
  borderColor: '#A5D6A7',
},
scanOverlay: {
  ...StyleSheet.absoluteFillObject,
  justifyContent: 'center',
  alignItems: 'center',
  backgroundColor: 'rgba(0,0,0,0.1)',
},
scanArea: {
  width: 250,
  height: 250,
  justifyContent: 'center',
  alignItems: 'center',
},
scanAreaBorder: {
  width: '90%',
  height: '90%',
  borderWidth: 3,
  borderColor: "#00E676",
  borderRadius: 10,
  borderStyle: 'dashed',
},
backButton: {
  position: 'absolute',
  top: 50,
  left: 20,
  backgroundColor: 'rgba(0,0,0,0.5)',
  borderRadius: 34,
  padding: 10,
},
flipButton: {
  position: 'absolute',
  bottom: 30,
  right: 20,
  backgroundColor: 'rgba(0,0,0,0.9)',
  borderRadius: 30,
  padding: 10,
},
  buttonContainer: {
    position: 'absolute',
    bottom: 25,
    left: 15,
    right: 15,
    padding: 25,
  },
  actionButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 18,
    paddingHorizontal: 20,
    borderRadius: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
    transform: [{ scale: 1 }],
  },
  scanButton: {
    backgroundColor: '#2E8B57',
    background: 'linear-gradient(135deg, #2E8B57 0%, #3CB371 100%)',
  },
  locationButton: {
    backgroundColor: '#20B2AA',
    background: 'linear-gradient(135deg, #20B2AA 0%, #48D1CC 100%)',
  },
  activeButton: {
    backgroundColor: '#4CAF50',
    background: 'linear-gradient(135deg, #4CAF50 0%, #66BB6A 100%)',
  },
  inactiveButton: {
    backgroundColor: '#78909C',
    background: 'linear-gradient(135deg, #78909C 0%, #90A4AE 100%)',
  },
  buttonText: {
    color: "white",
    fontSize: 18,
    fontWeight: "700",
    marginLeft: 12,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  messageContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 18,
    borderRadius: 15,
    marginHorizontal: 20,
    marginTop: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.05)',
  },
  errorContainer: {
    borderLeftWidth: 6,
    borderLeftColor: '#F44336',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderTopRightRadius: 15,
    borderBottomRightRadius: 15,
  },
  successContainer: {
    borderLeftWidth: 6,
    borderLeftColor: '#4CAF50',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderTopRightRadius: 15,
    borderBottomRightRadius: 15,
  },
  statusText: {
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 12,
    color: '#2C3E50',
    lineHeight: 22,
  },
  backButton: {
    position: "absolute",
    left: 25,
    top: 55,
    backgroundColor: "rgba(0,0,0,0.7)",
    padding: 12,
    borderRadius: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(248, 253, 248, 0.9)',
    zIndex: 1000,
  },
  
  // New Statistics Card Styles
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginTop: 20,
    marginBottom: 5,
  },
  
  statCard: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(212, 234, 218, 0.98)',
    borderRadius: 20,
    padding: 18,
    marginHorizontal: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 6,
    borderWidth: 1,
    borderColor: 'rgba(46, 139, 87, 0.08)',
  },
  
  statIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(46, 139, 87, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  
  statTextContainer: {
    flex: 1,
  },
  
  statLabel: {
    fontSize: 12,
    fontWeight: '500',
    color: '#7A7A7A',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  
  statValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2E8B57',
    textShadowColor: 'rgba(46, 139, 87, 0.2)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  
  // Fixed Message Overlay Styles
  messageOverlay: {
    position: 'absolute',
    top: height * 0.65,
    left: 20,
    right: 20,
    zIndex: 999,
    alignItems: 'center',
  },
  
  messageContent: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(46, 139, 87, 0.95)',
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderRadius: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  }, 
  messageText: {
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 12,
    color: '#FFFFFF',
    textAlign: 'center',
  },
  scanButtonContainer: {
    alignItems: 'center',
    marginBottom: 15,
    marginTop: 10,
  },
  circularScanButton: {
    width: 90,
    height: 90,
    borderRadius: 45,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#2E8B57',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 10,
    marginBottom: 8,
    borderWidth: 3,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  scanButtonLabel: {
    color: '#2E8B57',
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
    textShadowColor: 'rgba(46, 139, 87, 0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  secondaryButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  secondaryButton: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 15,
    paddingHorizontal: 15,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  activeSecondaryButton: {
    backgroundColor: '#4CAF50',
  },
  inactiveSecondaryButton: {
    backgroundColor: '#78909C',
  },
  locationSecondaryButton: {
    backgroundColor: '#20B2AA',
  },
  secondaryButtonText: {
    color: "white",
    fontSize: 14,
    fontWeight: "700",
    marginLeft: 8,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 1,
  },
});