import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  gradient: {
    flex: 1,
  },
  container: {
    flexGrow: 1,
    paddingVertical: 25,
    paddingHorizontal: 5,
  },
  contentContainer: {
    width: '100%',
    padding: 20,
    justifyContent: 'center',
  },
  topSection: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 25,
    paddingHorizontal: 5,
  },
  logo: {
    width: 70,
    height: 70,
    borderRadius: 35,
    marginRight: 20,
    borderWidth: 3,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  welcomeTextContainer: {
    flexDirection: 'column',
    flex: 1,
  },
  helloText: {
    fontSize: 24,
    fontWeight: '700',
    color: '#ffffff',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  welcomeText: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.9)',
    fontWeight: '500',
    marginTop: 2,
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 25,
    paddingHorizontal: 10,
  },
  statCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 20,
    padding: 20,
    flex: 0.48,
    alignItems: 'center',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(76, 175, 80, 0.2)',
  },
  statNumber: {
    fontSize: 28,
    fontWeight: '800',
    color: '#1b5e20',
    marginBottom: 5,
  },
  statText: {
    fontSize: 14,
    color: '#2e7d32',
    fontWeight: '600',
    textAlign: 'center',
  },
  card: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 25,
    padding: 25,
    marginBottom: 20,
    marginHorizontal: 5,
    elevation: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(76, 175, 80, 0.2)',
  },
  sectionTitle: {
    fontWeight: '700',
    marginBottom: 20,
    fontSize: 20,
    color: '#1b5e20',
    textAlign: 'center',
  },
  input: {
    borderWidth: 2,
    borderColor: '#81c784',
    padding: 18,
    marginVertical: 12,
    borderRadius: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    fontSize: 16,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  actionButton: {
    padding: 18,
    borderRadius: 15,
    marginVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    minHeight: 55,
  },
  generateButton: {
    backgroundColor: '#2e7d32',
    borderWidth: 2,
    borderColor: '#4caf50',
  },
  downloadButton: {
    backgroundColor: '#388e3c',
    borderWidth: 2,
    borderColor: '#66bb6a',
  },
  pdfButton: {
    backgroundColor: '#43a047',
    borderWidth: 2,
    borderColor: '#81c784',
  },
  buttonText: {
    color: '#ffffff',
    fontWeight: '700',
    textAlign: 'center',
    marginLeft: 8,
    fontSize: 16,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  buttonIcon: {
    marginRight: 8,
  },
  scrollContainer: {
    marginTop: 15,
  },
  qrScrollContainer: {
    maxHeight: 450,
    borderWidth: 1,
    borderColor: '#4caf50',
    borderRadius: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    marginTop: 10,
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  qrRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-evenly',
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  qrContainer: {
    marginVertical: 20,
    marginHorizontal: 10,
    alignItems: 'center',
    width: '40%',
    marginBottom: 20,
  },
  qrImageContainer: {
    backgroundColor: '#ffffff',
    padding: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#4caf50',
    marginBottom: 10,
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
  },
  qrCode: {
    width: 110,
    height: 110,
    borderRadius: 8,
  },
  qrLabel: {
    fontSize: 14,
    color: '#1b5e20',
    fontWeight: '600',
    textAlign: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 1,
    overflow: 'hidden',
  },
});