/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/buyer`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/collector`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/manufacturer`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/task-handler`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/register`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard/buyer`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard/collector`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard/manufacturer`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard/task-handler`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/forgot-password${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/register${`?${string}` | `#${string}` | ''}` | `/dashboard/buyer${`?${string}` | `#${string}` | ''}` | `/dashboard/collector${`?${string}` | `#${string}` | ''}` | `/dashboard/manufacturer${`?${string}` | `#${string}` | ''}` | `/dashboard/task-handler${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/buyer`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/collector`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/manufacturer`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/task-handler`; params?: Router.UnknownInputParams; };
    }
  }
}
